### PR TITLE
Update info_about_os.sh

### PR DESCRIPTION
**Pull request by AbhiTheModder**
- When we're getting Kernel info already through `-r` then doesn't it looks ugly to see the same thing and weird long line in OS name :)
- Looks ugly to see path to shell the current shell, for ex. if we're on Termux (Android) it shows lengthy line like `/data/data/com.termux/files/user/bin/bash`

### CODE REVIEW

**Comment by andresgongora** [comment]
Hi, thanks for you contribution!!
I can't accept this one as is quite yet. Would it be OK if I add support for it through other means? My rationale is:
- `uname -o` looses important information about kernel and distro versions
- `$(basename "$SHELL")` looks neater, I agree with you. Still, I suspect most sysadmins need to some extent info about the exact terminal emulator they are running.
If you are OK I can revamp your commit to create a new pair of options

**Comment by andresgongora** [comment]
Ahh OK I see what's going on wiht `os_name=$(uname -o)`, there is indeed another line to get the kernel info, so it would be reduntant. You are right!!

**Comment by andresgongora** [comment]
Ok! I've incorporated `$(basename "$SHELL")` into synth-shell-greeter and created a separate option to retain the full shell dir for those who need it. Kindly remove that bit from your pull request and then we can merge the part with `uname -o`

**Comment by AbhiTheModder** [comment]
>       If you are OK I can revamp your commit to create a new pair of options

Yeah, That is also a nice idea, thanks for this and your work ❤️

**Comment by andresgongora** [comment]
Thanks for your contribution!! :)
I think you also had an open PR to add your user's config. Feel free to reopen it if you want

**Pull request closed without merging**
